{% set name = "impactx" %}
{% set version = "25.02" %}
{% set build = 0 %}
{% set sha256 = "0e5702cfd27746bef1fcbf9207c86f817e99dce9f47c4440747b0ad1c227ef8e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BLAST-ImpactX/impactx/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [python_impl == 'pypy']
  run_exports:
    # releases are not (yet) compatible
    - impactx {{ version }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - clang         # [win]
    - cmake
    - lld           # [win]
    - libgomp       # [linux]
    - llvm-openmp   # [osx or win]
    - make          # [unix]
    - ninja         # [win]
    - pkg-config
  host:
    - amrex ={{ version }}
    - fftw
    # https://github.com/conda-forge/scipy-feedstock/issues/257#issuecomment-1792217861
    - libblas =*=*blis  # [win]
    - numpy
    - openpmd-api
    - pip
    - pyamrex ={{ version }}
    - pybind11
    - pybind11-abi
    - python
    - setuptools
    - wheel
  run:
    # see requirements.txt
    # https://github.com/conda-forge/scipy-feedstock/issues/257#issuecomment-1792217861
    - libblas =*=*blis  # [win]
    - python
    - pyamrex ={{ version }}
    - quantiphy
    # see src/python/impactx/dashboard/requirements.txt
    - pandas
    - plotly
    - trame
    - trame-matplotlib
    - trame-plotly
    - trame-router
    - trame-vuetify
    - trame-xterm

test:
  requires:
    - python
    - pytest
    # ctest, see examples/requirements.txt
    - matplotlib       # [build_platform == target_platform]
    - openpmd-api      # [build_platform == target_platform]
    - pandas           # [build_platform == target_platform]
    - pytest           # [build_platform == target_platform]
    - scipy            # [build_platform == target_platform]
    # https://github.com/conda-forge/scipy-feedstock/issues/257#issuecomment-1792217861
    - libblas =*=*blis  # [build_platform == target_platform and win]
  source_files:
    - examples/fodo/input_fodo.in
    - examples/fodo/run_fodo.py
    - tests/python/
    - examples/chicane/input_chicane_csr.in
  files:
    - test.sh   # [unix]
    - test.bat  # [win]
  imports:
    - impactx
  commands:
    - test -f ${PREFIX}/bin/impactx.NOMPI.OMP.DP.OPMD  # [unix]
    - if not exist %LIBRARY_PREFIX%\bin\impactx.NOMPI.OMP.DP.OPMD.exe exit 1  # [win]
    # smoke tests: execute
    - ./test.sh      # [unix and build_platform == target_platform]
    - call test.bat  # [win]

about:
  home: https://impactx.readthedocs.io
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE.txt
  summary: ImpactX is an s-based beam dynamics code for particle accelerator research & design.

  description: |
    ImpactX is an s-based beam dynamics code for particle accelerator research & design.
    It's the next generation of the IMPACT-Z code.

  doc_url: https://impactx.readthedocs.io
  dev_url: https://github.com/BLAST-ImpactX/impactx

extra:
  recipe-maintainers:
    - ax3l
    - cemitch99
    - EZoni
    - n01r
    - RemiLehe
