schema_version: 1

context:
  name: impactx
  version: "25.04"
  build: 0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/BLAST-ImpactX/impactx/archive/${{ version }}.tar.gz
  sha256: 2e5fb76f86d319303022c2a4f7c3cfc36f8dd5e1329d4f41865fdf8061f58025

build:
  skip: python_impl == "pypy"
  number: ${{ build }}

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pybind11
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - if: unix
      then: make
    - if: win
      then:
        - clang
        - lld
        - llvm-openmp
        - ninja
    - if: linux
      then: libgomp
    - if: osx
      then: llvm-openmp
    - cmake
    - pkg-config

  host:
    - amrex ==${{ version }}[build=nompi_*]
    - fftw
    - if: win
      then:
        # https://github.com/conda-forge/scipy-feedstock/issues/257#issuecomment-1792217861
        - libblas * [build=*blis]
    - numpy
    - openpmd-api * [build=nompi_*]
    - pip
    - pyamrex ==${{ version }}[build=nompi_*]
    - pybind11
    - pybind11-abi
    - python
    - setuptools
    - wheel
  run:
    - if: win
      then:
        # https://github.com/conda-forge/scipy-feedstock/issues/257#issuecomment-1792217861
        - libblas * [build=*blis]
    # see requirements.txt
    - pyamrex ==${{ version }}[build=nompi_*]
    - python
    - scipy
    - quantiphy
    # see src/python/impactx/dashboard/requirements.txt
    - pandas
    - plotly
    - trame
    - trame-matplotlib
    - trame-plotly
    - trame-router
    - trame-vuetify
    - trame-xterm

  run_exports:
    # releases are not (yet) compatible
    - impactx ==${{ version }}

tests:
  - python:
      imports:
        - impactx
      pip_check: false
  - package_contents:
      files:
        - if: unix
          then:
            - bin/impactx.NOMPI.OMP.DP.OPMD
        - if: win
          then:
            - Library/bin/impactx.NOMPI.OMP.DP.OPMD.exe

  - script:
      - echo "Testing..."
      - if: unix and (build_platform == target_platform)
        then: ./test.sh
      - if: win
        then: call test.bat
    requirements:
      run:
        - python
        - pytest
        # ctest, see examples/requirements.txt
        # TODO: PyNAFF
        - if: build_platform == target_platform
          then:
            - matplotlib
            - if: win
              then:
            # https://github.com/conda-forge/scipy-feedstock/issues/257#issuecomment-1792217861
                - libblas * [build=*blis]
    files:
      recipe:
        - if: unix
          then: test.sh
        - if: win
          then: test.bat
      source:
        - examples/fodo/input_fodo.in
        - examples/fodo/run_fodo.py
        - tests/python/
        - examples/chicane/input_chicane_csr.in

about:
  license: BSD-3-Clause-LBNL
  license_file: LICENSE.txt
  summary: ImpactX enables high-performance modeling of beam dynamics in particle accelerators with collective effects.
  description: |
    ImpactX enables high-performance modeling of beam dynamics in particle accelerators with collective effects.

    This is the next generation of the IMPACT-Z code. ImpactX runs on modern
    GPUs or CPUs alike, provides user-friendly interfaces suitable for AI/ML
    workflows, has many benchmarks to ensure its correctness, and an extensive
    documentation.
  homepage: https://impactx.readthedocs.io
  repository: https://github.com/BLAST-ImpactX/impactx
  documentation: https://impactx.readthedocs.io

extra:
  recipe-maintainers:
    - ax3l
    - cemitch99
    - EZoni
    - n01r
    - RemiLehe
